disabled_rules:
  - function_body_length
  - type_body_length
  - line_length
  - file_length
  - large_tuple
  - orphaned_doc_comment
included: # paths to include during linting. `--path` is ignored if present.
  - retroquestTests
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - r
    - g
    - b
    - a
    - RetroQuestServerURL
    - AppCenterSecret
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
