name: Build

on:
  push:
    branches: [ master, build-via-actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Write retroquest server file
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: retroquest/Generated/RetroquestServerURL.generated.swift
        contents: public let RetroQuestServerURL = "http://localhost:8080"
        
    - name: Write app center file
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: retroquest/Generated/AppCenterSecret.generated.swift
        contents: public let AppCenterSecret = "123"
        
    - name: xcodegen
      uses: xavierLowmiller/xcodegen-action@1.1.2
      
    - name: Build
      run: xcodebuild clean test -project retroquest.xcodeproj -scheme retroquest -destination 'platform=iOS Simulator,name=iPhone 8' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
