name: Build

on:
  push:
    branches: [ master, build-via-actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Write env variables
      uses: javajawa/create-envfile@v1
      with:
        file_name: env-vars.sh
        envkey_RETROQUEST_SERVER_URL: localhost:8080
        envkey_APP_CENTER_SECRET: 123
        
    - name: view env vars
      run: cat ./env-vars.sh
        
    - name: xcodegen
      uses: xavierLowmiller/xcodegen-action@1.1.2

    - name: Brew Install
      run: brew install sourcery
      
    #- name: Build
    #  run: xcodebuild clean test -project retroquest.xcodeproj -scheme retroquest -destination 'platform=iOS Simulator,name=iPhone 8' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
