name: Build

on:
  push:
    branches: [ master, build-via-actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Write env variables
      uses: DamianReeves/write-file-action@v1.0
      with:
        # The path to the file to write
        path: ./env-vars.sh
        # The contents of the file
        contents: export RETROQUEST_SERVER_URL=localhost:8080;export APP_CENTER_SECRET=123
        
    - name: xcodegen
      uses: xavierLowmiller/xcodegen-action@1.1.2

    - name: Brew Install
      run: brew install sourcery
      
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v
