name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Write env variables
      uses: DamianReeves/write-file-action@v1.0
      with:
        # The path to the file to write
        path: ./env-vars.sh
        # The contents of the file
        contents: export RETROQUEST_SERVER_URL=localhost:8080;export APP_CENTER_SECRET=123
    
    - name: view env vars
      run: cat ./env-vars.sh
    
    - name: Brew Install
      run: brew bundle --no-upgrade
    
    - name: Bundle Install
      run: bundle install
    
    - name: Get AppCenter
      run: make get_app_center
    
    - name: Build and test
      env: 
          FASTLANE_EXPLICIT_OPEN_SIMULATOR: "2"
      run: bundle exec fastlane tests
